# [Takumi Setup Wizard]
# This script configures '.wslconfig' automatically based on your system RAM.

try {
    # 1. Get Total Physical Memory (GB)
    $sysInfo = Get-CimInstance -ClassName Win32_ComputerSystem
    $totalRamGB = [math]::Round($sysInfo.TotalPhysicalMemory / 1GB)

    Write-Host ">>> System RAM Detected: ${totalRamGB} GB" -ForegroundColor Cyan

    # 2. Calculate Allocation
    $wslRam = [math]::Floor($totalRamGB * 0.75)
    if (($totalRamGB - $wslRam) < 4) { $wslRam = $totalRamGB - 4 }
    if ($wslRam -lt 4) { $wslRam = 4 }
    $swapSize = $totalRamGB

    Write-Host ">>> Recommended Configuration:" -ForegroundColor Green
    Write-Host "    Memory: ${wslRam}GB"
    Write-Host "    Swap:   ${swapSize}GB"

    # 3. Prepare Config Content
    $ConfigPath = "$env:USERPROFILE\.wslconfig"
    $Content = @"
[wsl2]
# Automatically generated by Takumi Setup
# System RAM: ${totalRamGB}GB
memory=${wslRam}GB
swap=${swapSize}GB
localhostForwarding=true
"@

    # 4. Write File
    if (Test-Path $ConfigPath) {
        Write-Host "⚠️  .wslconfig already exists at $ConfigPath" -ForegroundColor Yellow
        $confirmation = Read-Host "Overwrite? (y/n)"
        if ($confirmation -ne 'y') {
            Write-Host "Cancelled."
            Read-Host "Press Enter to exit..."
            exit
        }
    }

    Set-Content -Path $ConfigPath -Value $Content
    Write-Host "✅ Configuration saved to $ConfigPath" -ForegroundColor Green
    
    Write-Host "🔄 Restarting WSL..." -ForegroundColor Cyan
    wsl --shutdown
    
    Write-Host "✨ Done! You can now launch Takumi Enterprise." -ForegroundColor Green

} catch {
    Write-Host "❌ Error: $($_.Exception.Message)" -ForegroundColor Red
}

# Wait to close the window immediately
Read-Host "Press Enter to exit..."